spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://BOOKSERVICEB
              predicates:
                - Path=/books/**
            - id: order-service
              uri: lb://ORDERSERVICEA
              predicates:
                - Path=/orders/**